// Generated by gencpp from file utils/subscribing.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SUBSCRIBING_H
#define UTILS_MESSAGE_SUBSCRIBING_H

#include <ros/service_traits.h>


#include <utils/subscribingRequest.h>
#include <utils/subscribingResponse.h>


namespace utils
{

struct subscribing
{

typedef subscribingRequest Request;
typedef subscribingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct subscribing
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::subscribing > {
  static const char* value()
  {
    return "e12d1d601f3408b19cc7b794aab7c96f";
  }

  static const char* value(const ::utils::subscribing&) { return value(); }
};

template<>
struct DataType< ::utils::subscribing > {
  static const char* value()
  {
    return "utils/subscribing";
  }

  static const char* value(const ::utils::subscribing&) { return value(); }
};


// service_traits::MD5Sum< ::utils::subscribingRequest> should match
// service_traits::MD5Sum< ::utils::subscribing >
template<>
struct MD5Sum< ::utils::subscribingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::subscribing >::value();
  }
  static const char* value(const ::utils::subscribingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::subscribingRequest> should match
// service_traits::DataType< ::utils::subscribing >
template<>
struct DataType< ::utils::subscribingRequest>
{
  static const char* value()
  {
    return DataType< ::utils::subscribing >::value();
  }
  static const char* value(const ::utils::subscribingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::subscribingResponse> should match
// service_traits::MD5Sum< ::utils::subscribing >
template<>
struct MD5Sum< ::utils::subscribingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::subscribing >::value();
  }
  static const char* value(const ::utils::subscribingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::subscribingResponse> should match
// service_traits::DataType< ::utils::subscribing >
template<>
struct DataType< ::utils::subscribingResponse>
{
  static const char* value()
  {
    return DataType< ::utils::subscribing >::value();
  }
  static const char* value(const ::utils::subscribingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_SUBSCRIBING_H
