// Generated by gencpp from file utils/subscribingResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SUBSCRIBINGRESPONSE_H
#define UTILS_MESSAGE_SUBSCRIBINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct subscribingResponse_
{
  typedef subscribingResponse_<ContainerAllocator> Type;

  subscribingResponse_()
    : topic(false)  {
    }
  subscribingResponse_(const ContainerAllocator& _alloc)
    : topic(false)  {
  (void)_alloc;
    }



   typedef uint8_t _topic_type;
  _topic_type topic;





  typedef boost::shared_ptr< ::utils::subscribingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::subscribingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct subscribingResponse_

typedef ::utils::subscribingResponse_<std::allocator<void> > subscribingResponse;

typedef boost::shared_ptr< ::utils::subscribingResponse > subscribingResponsePtr;
typedef boost::shared_ptr< ::utils::subscribingResponse const> subscribingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::subscribingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::subscribingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::subscribingResponse_<ContainerAllocator1> & lhs, const ::utils::subscribingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.topic == rhs.topic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::subscribingResponse_<ContainerAllocator1> & lhs, const ::utils::subscribingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::subscribingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::subscribingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::subscribingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::subscribingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::subscribingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::subscribingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::subscribingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4e79895ca3da0c8b6ee070f82d72fff";
  }

  static const char* value(const ::utils::subscribingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4e79895ca3da0c8ULL;
  static const uint64_t static_value2 = 0xb6ee070f82d72fffULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::subscribingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/subscribingResponse";
  }

  static const char* value(const ::utils::subscribingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::subscribingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool topic\n"
;
  }

  static const char* value(const ::utils::subscribingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::subscribingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct subscribingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::subscribingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::subscribingResponse_<ContainerAllocator>& v)
  {
    s << indent << "topic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.topic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_SUBSCRIBINGRESPONSE_H
